### ISSUE TITLE
Allow all configuration supported by FaviconsWebpackPlugin

### ISSUE THREAD

**Issue by aaronsky** [Creatiwity/gatsby-plugin-favicon#12]
Hey folks, real happy with the plugin. Y'all made my site much easier to deploy yesterday. 👍 

One thing I'd like to see is being able to pass through all options supported by FaviconsWebpackPlugin, rather than just the icons object and logo path. It'd be really great to get the full swath of features that plugin makes available.

**Comment by julien1619** [comment]
Hello! Thank you for your feedbacks :)
It seems to be an easy task, I can look into it maybe at the end of the week or next week, or if it's really needed quickly you can submit a PR implementing this feature.

**Comment by julien1619** [comment]
Done with the latest version.
