### ISSUE TITLE
package.json Illegal characters

### ISSUE THREAD

**Issue by levinstanley** [Creatiwity/gatsby-plugin-favicon#13]
Hey, I'm getting the following error:

$ yarn add gatsby-plugin-favicon
yarn add v1.3.2
error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Any thoughts?

**Comment by julien1619** [comment]
I didn't have any problem, can you still reproduce the bug? Don't hesitate to reopen the bug if it's the case :)
