### ISSUE TITLE
Is it possible to customize the `manifest.json`?

### ISSUE THREAD

**Issue by phlipper** [Creatiwity/gatsby-plugin-favicon#18]
Hello,

Thank you for this plugin! Is it, or could it be, possible to customize the generated `manifest.json` file? I'd like to be able to set the `name`, `short_name`, `description`, `start_url`, etc.

**Comment by moonmeister** [comment]
I'd second this need. I'd be happy to look into adding this feature. @creatiwity would you take a PR for this? My goal would basically to combined the functionality with the [gatsby-plugin-manifest](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-manifest). cc: @KyleAMathews

**Comment by julien1619** [comment]
Thank you for the feedback! It's been a long time but the version 3.1.0 is just out right now and supports a full manifest configuration with Gatsby v2.
