### ISSUE TITLE
Compatibility: Latest Gatsby "onRenderBody" is not an API method

### ISSUE THREAD

**Issue by gregorskii** [Creatiwity/gatsby-plugin-favicon#19]
Seems to be an issue with latest Gatsby:

```
See https://www.gatsbyjs.org/docs/ssr-apis/ for the list of Gatsby SSR APIs
 — The plugin "gatsby-plugin-favicon@2.1.1" is exporting a variable named "onRenderBody" which isn't an API.
```

Packages:

```
"gatsby": "^1.9.158",
"gatsby-plugin-favicon": "^2.1.1"
```

**Comment by mperkh** [comment]
Just tired it, using a vanilla installation and can not reproduce this issue. Nothing seems to have changed at https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody

**Comment by s-kennedy** [comment]
I'm getting this error too, any updates?

**Comment by julien1619** [comment]
The new version supports Gatsby v2, so it shouldn't be a problem anymore.
