### ISSUE TITLE
Option to convert favicon.png to favicon.webp?

### ISSUE THREAD

**Issue by ooloth** [Creatiwity/gatsby-plugin-favicon#21]
Any chance of an option to convert favicon.png to favicon.webp?

A Lighthouse performance audit of a site using gatsby-plugin-favicon includes the following recommendation:

```
Serve images as WebP: 

WebP provides better lossy and lossless compression than PNG or JPEG, 
which means faster downloads and less data consumption.

Potential savings: 8 KB (70%)
```

Normally, I can use `...GatsbyImageSharpSizes_withWebp` when querying images, but obviously that isn't available here. 

Any help would be appreciated! I imagine most Gatsby users are as performance-obsessed as I am. 😉

**Comment by mperkh** [comment]
Could'nt find much about favicons in WebP format online. Would that just mean, a favicon.webp file should be generated? How is that injected into html?

Seems https://github.com/jantimon/favicons-webpack-plugin, which itself is using https://github.com/evilebottnawi/favicons to generate the icons, does not support that.

**Comment by ooloth** [comment]
Yeah, I haven't heard of using WebP for favicons either, but it seems like it might be a good (if new) idea where possible. (We're talking a difference of ~7KB though, so it's not a major concern.)

I hadn't noticed this project's dependencies, so thanks for explaining those constraints. 

What I'd noticed is that the PNGs are all hard coded in [https://github.com/Creatiwity/gatsby-plugin-favicon/blob/master/src/gatsby-ssr.js](https://github.com/Creatiwity/gatsby-plugin-favicon/blob/master/src/gatsby-ssr.js) and I was imagining somehow using Sharp to generate Webp versions that could be injected instead, but perhaps that isn't feasible in this case.

**Comment by julien1619** [comment]
I think it's a feature that should be added to the module generating icons. Maybe you should open a feature request on https://github.com/itgalaxy/favicons, I'm closing it here.
