### ISSUE TITLE
Add content hashes to output filenames

### ISSUE THREAD

**Issue by tremby** [Creatiwity/gatsby-plugin-favicon#24]
To allow long-term caching.

Consider changing the default output directory to be under "static" at that point too, along with other things which can be cached long-term.

**Comment by julien1619** [comment]
I've just published an update with hashes on filenames and favicon folder.

**Comment by karolis-sh** [comment]
The output now is at `public/icon-[hash]/...` but following the [gatsby docs](https://www.gatsbyjs.org/docs/caching/) wouldn't it be more accurate to output at `public/static/icon-[hash]/...`? This would simplify the cache setup for servers.

Ahh, it's actually possible via options:

```js
    {
      resolve: 'gatsby-plugin-favicon',
      options: {
        prefix: 'static/icons-[hash]/',
      },
    },
```

**Comment by julien1619** [comment]
You're right, we should change the value to enforce good practice.
