### ISSUE TITLE
favicon disapears

### ISSUE THREAD

**Issue by decimoseptimo** [Creatiwity/gatsby-plugin-favicon#26]
chrome latest (66), to reproduce:
enter `/page.html`
click any external link
click on browser's back button 
click on `anotherPage.html`
click on `/page.html`
At this point the favicon dissapears from the window

IE11, to reproduce:
enter `index.html`
as soon as you change page the favicon will disapear
unless you're at `index.html`

This doesn't happen when "manual" favicon.ico insertion takes place.
I haven't tested other sites since I'm not aware of sites using this plugin, but you can check my profile link for a live implementation.

**Comment by julien1619** [comment]
Thanks for the report! I'll look into it quickly. In fact I've had some strange behavior with Gatsby lately, maybe it's related to what you're experiencing.

**Comment by julien1619** [comment]
Do you still have the bug with Gatsby v2 and the update of the plugin?

**Comment by decimoseptimo** [comment]
I'm not very fond of betas. Let's keep this on hold.

**Comment by julien1619** [comment]
Ok, so I'm closing it for now, feel free to reopen it if needed.
