### ISSUE TITLE
White background on Apple icons

### ISSUE THREAD

**Issue by lachlanjc** [Creatiwity/gatsby-plugin-favicon#28]
I have a favicon source PNG image with a transparent background, but when this plugin generates the Apple icons, it adds a white background, which looks sloppy. (mine below) I'd imagine this is a problem on Android as well.

<img width="100" alt="screen shot 2018-05-19 at 4 58 36 pm" src="https://user-images.githubusercontent.com/5074763/40272988-0c2cd436-5b86-11e8-8a97-8b050526b426.png">

**Comment by DJTB** [comment]
This is just how iOS works - the plugin doesn't add the white background, iOS does for any alpha.
https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon

Android is fine with transparency.

**Comment by lachlanjc** [comment]
iOS does that when adding the app to the home screen, but as in the screenshot, transparent layers are utilized in Safari on macOS/iOS

**Comment by arjunattam** [comment]
Same issue here as well. Did you discover any fixes @lachlanjc?

<img width="104" alt="screen shot 2018-06-07 at 12 26 00 pm" src="https://user-images.githubusercontent.com/284612/41083089-f6a56cd2-6a4d-11e8-9283-68ef2c80a53b.png">

**Comment by arjunattam** [comment]
Looks like this is coming from two levels upstream. Related issue: https://github.com/evilebottnawi/favicons/issues/173

There is a configuration option in the favicons package, called `background`, which is set at #fff. Not sure if that is exposed downstream

**Comment by julien1619** [comment]
I've just exposed `background` as a configuration option of this plugin. I'll pack it as a new update very soon!

**Comment by julien1619** [comment]
An update for Gatsby v2 is available with `background`exposed.

**Comment by Undistraction** [comment]
@julien1619 It looks like `background` only accepts hex colours. Is there any way to set it to transparent?
