### ISSUE TITLE
Favicon.png dimension

### ISSUE THREAD

**Issue by bernatfortet** [Creatiwity/gatsby-plugin-favicon#3]
Which should be the size of the favicon to rescale properly?

Thanks

**Comment by mperkh** [comment]
The test image of https://github.com/evilebottnawi/favicons, which this gatsbyJS plugin depends on, has a dimension of 1.500 x 1.500 pixels. So I would say the image should be at least that size.

https://github.com/evilebottnawi/favicons/blob/master/test/logo.png

**Comment by julien1619** [comment]
That's right, 1500x1500 should be enough. I'll keep this issue opened for now until I add it to the README file.
