### ISSUE TITLE
Paths are prefixed even when --prefix-paths is not set

### ISSUE THREAD

**Issue by Mrtenz** [Creatiwity/gatsby-plugin-favicon#30]
If I run `gatsby build` without `--prefix-paths`, the paths in the HTML still refer to `/[prefix]/favicons`. Not a big deal, since the production builds require `--prefix-paths`, but it would be nice if this could be fixed.

**Comment by Mrtenz** [comment]
I just noticed #25, but it looks like this is not published to npm yet?

**Comment by julien1619** [comment]
A new update is available for Gatsby v2 and it fixes it.
