### ISSUE TITLE
error compiling with default settings

### ISSUE THREAD

**Issue by endymion1818** [Creatiwity/gatsby-plugin-favicon#39]
Hi,

This is a really useful plugin, however I'm running into the following issue when running `gatsby develop`

```
error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  71 |    * @internal
  72 |    */
> 73 |   enqueueReplaceState: function (publicInstance, completeState) {
     | ^
  74 |     warnNoop(publicInstance, 'replaceState');
  75 |   },
  76 |


  WebpackError: ENOENT: no such file or directory, open '/Users/ben.read/Sites/Shopfront/public/.iconstats.json'
```
I see a similar issue on running `gatsby build`

**Comment by InfraK** [comment]
It's happening the same to me.

**Comment by julien1619** [comment]
Hi! thanks for the report. The last major version 3.x of this plugin is only compatible with Gatsby v2 (currently in beta, but very close to RC I think). There is some work in progress to enable Gatsby v1 compatibility but there is one last bug preventing it from publishing.

Do you confirm both that you are using version 3 of this plugin with Gatsby v1?

**Comment by InfraK** [comment]
I am.

Which version supports gatsby v1?

**Comment by julien1619** [comment]
@InfraK 2.1.1
