### ISSUE TITLE
Initial install gives 'WebpackError: ENOENT: no such file or directory, open '/apps/foundrs/public/.iconstats.json'

### ISSUE THREAD

**Issue by stefl** [Creatiwity/gatsby-plugin-favicon#42]
I've just added this to a project using the default config, but I initially get the following in logs:

```
success write out page data — 0.003 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.000 s

info bootstrap finished - 2.943 s

error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  274 |  * Forces an update. This should only be invoked when it is known with
  275 |  * certainty that we are **not** in a DOM transaction.
> 276 |  *
      | ^
  277 |  * You may want to call this when you know that some deeper aspect of the
  278 |  * component's state has changed but `setState` was not called.
  279 |  *


  WebpackError: ENOENT: no such file or directory, open '/apps/foundrs/public/.iconstats.json'
```

**Comment by jeriscc** [comment]
I got the same error. Potential solutions?

**Comment by stefl** [comment]
@jeriscc I put this here more as a placeholder than anything, but I wasn't able to resolve this. Looking at the requirement for Node 0.12 and I'm using 0.10 seemed like a good candidate. However the other issues around memory usage seem problematic. I'm using Imgix elsewhere in my app so I may roll my own version of this that uses that for resizing instead.

**Comment by jeriscc** [comment]
@stefl So I just installed the `2.1.1` version and the issue was resolved. I think the reason might have been that I had Gatsby `1.9.277` which was incompatible with the latest version of this plugin (which needs `gatsby@^2.0.0-alpha`).

**Comment by stefl** [comment]
@jeriscc Thanks. Had a go, but the Gatsby 2 alpha blows up my SASS files.

**Comment by julien1619** [comment]
Hello! I've just published an update to add a workaround for Gatsby v1, but it will still fail for the first build. See the mention added to the README: https://github.com/Creatiwity/gatsby-plugin-favicon#gatsby-v1-workaround

I'll close this issue for now, feel free to open another one if needed. :)

**Comment by julien1619** [comment]
Change of plans. Badly, the last version of Gatsby doesn't let me export a v1 API in parallel with a v2 API. You will have to stick to the version 2.1.1 of this plugin with Gatsby v1. I added a mention about it in the README. Thanks again for the report.
