### ISSUE TITLE
plugin "gatsby-plugin-favicon@3.1.3" is exporting a variable named "modifyWebpackConfig" which isn't an API.

### ISSUE THREAD

**Issue by MayerMediaCo** [Creatiwity/gatsby-plugin-favicon#43]
Plugin started outputting this error only upon Netlify deploy which caused the build to fail.  Nothing has changed with the config of the plugin.  I have updated to 3.1.3 and am on Gatsby 2.0.0-rc.9

**Comment by julien1619** [comment]
I had a warning about it but not an error. It seems that the last version of Gatsby issues an error and not a warning anymore when exporting a v1 API.

In fact the last version of `gatsby-plugin-favicon` includes a workaround for Gatsby v1 users, so it seems I'll have to finally remove it. An new update will come in a few hours.

**Comment by julien1619** [comment]
Fixed by 1b4c0ba84d7fa2fc8ad8f36460456f8aa55094ac
