### ISSUE TITLE
WebpackError: Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by perteraul** [Creatiwity/gatsby-plugin-favicon#44]
Just tried to build the via Netlify without any options and this was the outcome of that. 

v2.1.1

**Comment by hamstercat** [comment]
I had the same problem, turns out there was no default options in v2.2.1. I used the README.md from here https://github.com/Creatiwity/gatsby-plugin-favicon/tree/v2.1.1 and had to add options to my plugin in gatsby-config.js.

```
{
  resolve: 'gatsby-plugin-favicon',
  options: {
    logo: './src/favicon.png',
    injectHTML: true,
    icons: {
      android: true,
      appleIcon: true,
      appleStartup: true,
      coast: false,
      favicons: true,
      firefox: true,
      twitter: false,
      yandex: false,
      windows: false
    }
  }
}
```

**Comment by babzcraig** [comment]
Thanks for this!

**Comment by julien1619** [comment]
Indeed there wasn't a working default configuration in 2.1.1. Please see https://github.com/Creatiwity/gatsby-plugin-favicon/tree/v2.1.1
