### ISSUE TITLE
WebpackError: ENOENT: no such file or directory, open /public/.iconstats.json'

### ISSUE THREAD

**Issue by aesign** [Creatiwity/gatsby-plugin-favicon#46]
- react.development.js:485 Object.fs.openSync
    ~/react/cjs/react.development.js:485:1
  
  - react.development.js:390 Object.fs.readFileSync
    ~/react/cjs/react.development.js:390:1
  
  - gatsby-ssr.js:8 Object.module.exports.onRenderBody
    ~/gatsby-plugin-favicon/gatsby-ssr.js:8:1
  
  - api-runner-ssr.js:31 
    .cache/api-runner-ssr.js:31:41
  
  
  - api-runner-ssr.js:29 module.exports
    .cache/api-runner-ssr.js:29:25
  
  - develop-static-entry.js:52 module.exports
    .cache/develop-static-entry.js:52:3
  
  - react.development.js:19 Function.Promise.fromNode.Promise.fromCallback
    ~/react/cjs/react.development.js:19:1
  
  
  
  
  
  
  - react.development.js:411 Compilation.<anonymous>
    ~/react/cjs/react.development.js:411:1
  
  
  - react.development.js:406 Compilation.<anonymous>
    ~/react/cjs/react.development.js:406:1
  
  - develop-static-entry.js:3 Compilation.next
    .cache/develop-static-entry.js:3:1
  
  - react.development.js:148 ExtractTextPlugin.<anonymous>
    ~/react/cjs/react.development.js:148:1
  
  
  - react.development.js:402 Compilation.<anonymous>
    ~/react/cjs/react.development.js:402:1
  
  - develop-static-entry.js:3 Compilation.next
    .cache/develop-static-entry.js:3:1

**Comment by julien1619** [comment]
Thanks for the report. I think you have Gatsby v1 and this plugin in version 3+, which are not compatible. The last version is only compatible with Gatsby v2 which is in RC right now.

https://github.com/Creatiwity/gatsby-plugin-favicon#gatsby-v1

**Comment by aesign** [comment]
Thanks! How can I downgrade this plugin to 2.1.1 in order to keep Gatsby v1? (I'm new to the React/Gatsby world)
