### ISSUE TITLE
(v2.1.1)  WebpackError: Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by aesign** [Creatiwity/gatsby-plugin-favicon#47]
- gatsby-ssr.js:16 Object.exports.onRenderBody
    ~/gatsby-plugin-favicon/gatsby-ssr.js:16:1
  
  - api-runner-ssr.js:31 
    .cache/api-runner-ssr.js:31:41
  
  
  - api-runner-ssr.js:29 module.exports
    .cache/api-runner-ssr.js:29:25
  
  - develop-static-entry.js:52 module.exports
    .cache/develop-static-entry.js:52:3
  
  - react.development.js:19 Function.Promise.fromNode.Promise.fromCallback
    ~/react/cjs/react.development.js:19:1

**Comment by julien1619** [comment]
Can you test the solution given a few days ago: https://github.com/Creatiwity/gatsby-plugin-favicon/issues/44 ? Thank you.

**Comment by aesign** [comment]
Sorry!
