### ISSUE TITLE
Err 137 with v2.1.1 in Gatsby 1.9.241

### ISSUE THREAD

**Issue by Kay2dan** [Creatiwity/gatsby-plugin-favicon#52]
Hello,

I have reviewed all the open & closed issues, however, haven't found any with the solution to my issue.

My package.json has the following relevant info:
```
...
  "dependencies": {
    "bloomer": "^0.6.3",
    "bulma": "^0.6.2",
    "font-awesome": "^4.7.0",
    "gatsby": "^1.9.241",
    "gatsby-link": "^1.6.39",
    "gatsby-plugin-favicon": "^2.1.1",
    "gatsby-plugin-react-helmet": "^2.0.8",
    "gatsby-plugin-sass": "1.0.19",
    "nuka-carousel": "^4.4.0",
    "react-helmet": "^5.2.0",
    "react-responsive": "^5.0.0",
    "react-scroll": "^1.7.10"
  },
...
```

My gatsby-config.js is as follows:
```
module.exports = {
  siteMetadata: {
    title: 'ph - Crypto wave',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass',
    {
      resolve: `gatsby-plugin-favicon`,
      options: {
        logo: './src/favicon.png',
        injectHTML: true,
        icons: {
          android: true,
          appleIcon: true,
          appleStartup: true,
          coast: false,
          favicons: true,
          firefox: true,
          twitter: false,
          yandex: false,
          windows: false,
        },
      },
    },
  ],
  pathPrefix: '/ph_website',
};
```

However, I am getting the npm exit status 137 with code ELIFECYCLE

What am I doing wrong and facing this error?

Thanks,

**Comment by Kay2dan** [comment]
Im closing this as I used an alternative method of appending a favicon as I couldn't get this to work.

**Comment by julien1619** [comment]
Hi! Thanks for the report. I have no idea why you've got this error.
Maybe if you update Gatsby to version 2 and this plugin to the last version you can make it work.

**Comment by Kay2dan** [comment]
Thanks for the feedback, in the end I just went ahead with ico file with the existing version. That resolved the requirement. Next time, will definitely use Gatsby 2. Thanks again.
