### ISSUE TITLE
Twitter and OpenGraph don't work

### ISSUE THREAD

**Issue by thetrevorharmon** [Creatiwity/gatsby-plugin-favicon#56]
I've been trying to use the the Twitter & OpenGraph flags, but after tracing back through the dependencies of this repo, it turns out that the code that actually generates the favicons (from [itgalaxy/favicons](https://github.com/itgalaxy/favicons)) doesn't generate Twitter or OpenGraph tags.

**Comment by julien1619** [comment]
Merged in develop, will be released soon. Thanks for the PR, sorry for the delay to merge it.
